force-app/main/default/objects/Subscriber__c/Subscriber__c.object-meta.xml
<CustomObject>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Subscriber Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscribers</relationshipLabel>
    <relationshipName>Subscribers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscriber__c/fields/Recent_Subscriber__c.field-meta.xml
<CustomField>
    <fullName>Recent_Subscriber__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Recent Subscriber</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SubscriberHandler.cls
public with sharing class SubscriberHandler {
    public static void handlerSubscribers(List<Subscriber__c> subscribers){
        Set<Id> accIds = new Set<Id>();
        for(Subscriber__c sub : subscribers){
            if(sub.Account__c != null){
                accIds.add(sub.Account__c);
            }
        }

        if(accIds.isEmpty()){
            return;
        }

        List<Subscriber__c> recentSubscriberList = [SELECT Id, Account__c FROM Subscriber__c WHERE Account__c IN : accIds ORDER BY CreatedDate DESC];
        Map<Id, Subscriber__c> recentSubMap = new Map<Id, Subscriber__c>();
        for(Subscriber__c sub : recentSubscriberList){
            if(!recentSubMap.containsKey(sub.Account__c)){
                sub.Recent_Subscriber__c = true;
                recentSubMap.put(sub.Account__c, sub);
            }else {
                sub.Recent_Subscriber__c = false;
            }
        }
        if(recentSubscriberList.isEmpty()){
            return;
        }

        Database.update(recentSubscriberList, false, AccessLevel.USER_MODE);
    }
}